/* Generated By:JavaCC: Do not edit this line. HtmlGrammarConstants.java */
package Test;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HtmlGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TAG_START = 3;
  /** RegularExpression Id. */
  int TAG_END = 4;
  /** RegularExpression Id. */
  int TAG_SLASHEND = 5;
  /** RegularExpression Id. */
  int ENDTAG_START = 6;
  /** RegularExpression Id. */
  int EQUAL = 7;
  /** RegularExpression Id. */
  int ALPHA_CHAR = 8;
  /** RegularExpression Id. */
  int NUM_CHAR = 9;
  /** RegularExpression Id. */
  int ALPHANUM_CHAR = 10;
  /** RegularExpression Id. */
  int IDENTIFIER_CHAR = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;
  /** RegularExpression Id. */
  int TAG_NAME = 13;
  /** RegularExpression Id. */
  int ATTRIBUTE_NAME = 14;
  /** RegularExpression Id. */
  int ATTRIBUTE_VALUE = 15;
  /** RegularExpression Id. */
  int EOL = 16;
  /** RegularExpression Id. */
  int WHITESPACE = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"<\"",
    "\">\"",
    "\"/>\"",
    "\"</\"",
    "\"=\"",
    "<ALPHA_CHAR>",
    "<NUM_CHAR>",
    "<ALPHANUM_CHAR>",
    "<IDENTIFIER_CHAR>",
    "<IDENTIFIER>",
    "<TAG_NAME>",
    "<ATTRIBUTE_NAME>",
    "<ATTRIBUTE_VALUE>",
    "<EOL>",
    "<WHITESPACE>",
  };

}
