/* Generated By:JavaCC: Do not edit this line. HtmlGrammarConstants.java */
package kr.ac.cau.popl.gauthierplm;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HtmlGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHA_CHAR = 4;
  /** RegularExpression Id. */
  int NUM_CHAR = 5;
  /** RegularExpression Id. */
  int ALPHANUM_CHAR = 6;
  /** RegularExpression Id. */
  int IDENTIFIER_CHAR = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int QUOTED_STRING_NB = 9;
  /** RegularExpression Id. */
  int QUOTED_STRING = 10;
  /** RegularExpression Id. */
  int WHITESPACE = 11;
  /** RegularExpression Id. */
  int NEWLINE = 12;
  /** RegularExpression Id. */
  int QUOTE = 13;
  /** RegularExpression Id. */
  int EOL = 14;
  /** RegularExpression Id. */
  int TAG_START = 15;
  /** RegularExpression Id. */
  int ENDTAG_START = 16;
  /** RegularExpression Id. */
  int COMMENT_START = 17;
  /** RegularExpression Id. */
  int DECL_START = 18;
  /** RegularExpression Id. */
  int TEXT = 19;
  /** RegularExpression Id. */
  int TAG_NAME = 20;
  /** RegularExpression Id. */
  int ATTR_NAME = 22;
  /** RegularExpression Id. */
  int TAG_END = 23;
  /** RegularExpression Id. */
  int TAG_SLASHEND = 24;
  /** RegularExpression Id. */
  int ATTR_EQ = 25;
  /** RegularExpression Id. */
  int ATTR_VAL = 27;
  /** RegularExpression Id. */
  int COMMENT_END = 28;
  /** RegularExpression Id. */
  int DASH = 29;
  /** RegularExpression Id. */
  int COMMENT_EOL = 30;
  /** RegularExpression Id. */
  int COMMENT_WORD = 31;
  /** RegularExpression Id. */
  int DECL_ANY = 32;
  /** RegularExpression Id. */
  int DECL_END = 33;

  /** Lexical state. */
  int LexDecl = 0;
  /** Lexical state. */
  int LexComment = 1;
  /** Lexical state. */
  int LexAttrVal = 2;
  /** Lexical state. */
  int LexInTag = 3;
  /** Lexical state. */
  int LexStartTag = 4;
  /** Lexical state. */
  int DEFAULT = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"=\\n\"",
    "\"=\\r\\n\"",
    "\"=\\r\"",
    "<ALPHA_CHAR>",
    "<NUM_CHAR>",
    "<ALPHANUM_CHAR>",
    "<IDENTIFIER_CHAR>",
    "<IDENTIFIER>",
    "<QUOTED_STRING_NB>",
    "<QUOTED_STRING>",
    "<WHITESPACE>",
    "<NEWLINE>",
    "<QUOTE>",
    "<EOL>",
    "\"<\"",
    "\"</\"",
    "\"<!--\"",
    "\"<!\"",
    "<TEXT>",
    "<TAG_NAME>",
    "<token of kind 21>",
    "<ATTR_NAME>",
    "\">\"",
    "\"/>\"",
    "\"=\"",
    "<token of kind 26>",
    "<ATTR_VAL>",
    "<COMMENT_END>",
    "\"-\"",
    "<COMMENT_EOL>",
    "<COMMENT_WORD>",
    "<DECL_ANY>",
    "\">\"",
  };

}
